url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Anjolaoluwa Popoola" # the name of your site, e.g. ACME Corp.
description: "PhD Machine Learning Student at Georgia Tech"
