menu:
- {name: 'Home', url: '/home'}
- {name: 'Publications', url: '/publications'}
- {name: 'Teaching and Service', url: '/teaching'}
- {name: 'CV', url: '/cv'}
- {name: 'Contact', url: '/contact'}

teaching:
- {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
- {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

education:
  - {degree: "PhD Student, Machine Learning", year: "Started 2021", institution: "Georgia Institute of Technology", advisor: "Dr. Kamran Paynabar", advisor_link: "https://www.isye.gatech.edu/users/kamran-paynabar", minor: "Health Systems Leadership"}
  - {degree: "MSc. in Operations Research", year: 2021, institution: "Georgia Institute of Technology"}
  - {degree: "BSc. in Mathematics", year: 2019, institution: "Lincoln University of Pennsylvania", minor: "Biology"}

awards:
  - {title_main: "George Fellowship", title_linked: "Georgia Institute of Technology", year: "2024", link_url: "https://www.isye.gatech.edu/academics/fellowships/george-fellowship-program"}
  - {title_main: "Future BA Prof Program Fellow", title_linked: "Tippie College of Business, University of Iowa", year: "2024", link_url: "https://tippie.uiowa.edu/news-events/events/business-analytics-futurebaprof"}
  - {title_main: "Trailblazers in Engineering Fellow", title_linked: "Purdue University", year: "2023", link_url: "https://engineering.purdue.edu/Engr/Trailblazers"}
  - {title_main: "Master Modeler Competition, Bronze Winner", title_linked: "Georgia Tech", year: "2022"}
  - {title_main: "Best Student Poster Award", title_linked: "Transportation Research Board Conference", year: "2018", link_url: "https://trb-annual-meeting.nationalacademies.org"}
  - {title_main: "Dwight David Eisenhower Transportation Fellowship", year: "2018", link_url: "https://highways.dot.gov/careers/dwight-david-eisenhower-transportation-fellowship-program"}

social:
- {icon: 'envelope', link: 'mailto:apopoola3@gatech.edu'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/anjpopoola/'}
- {icon: 'google scholar', link: 'https://scholar.google.com/citations?user=HnjeRToAAAAJ&hl=en&oi=ao'}
- {icon: 'researchgate', link: 'https://www.researchgate.net/profile/Anjolaoluwa-Popoola'}

contacts:
- {name: 'Anjolaoluwa Popoola', title: 'PhD. Machine Learning Student', department: 'H. Milton Stewart School of Industrial and Systems Engineering', institution: 'Georgia Institute of Technology', institution_address: '755 Ferst Dr NW, Atlanta, GA 30332', office: 'Main 435', email: 'apopoola3@gatech.edu', image: 'assets/img/headshot.jpg'}
